### ISSUE TITLE
Ta med brukertesting og resultater (flett inn igjen etter jeg har gjort den til engelsk)

### ISSUE THREAD

**Issue by haakonhp** [JarleSyvertsen/EstivateORM#31]
Oversette user testing til engelsk (Ferdig, ikke inkludert i hovedprosjektet enda)

**Comment by JarleSyvertsen** [comment]
Gjort til engelsk, trengs bare å finne et naturlig sted å flette inn.

**Comment by haakonhp** [comment]
Kapittel 4.4 / 4.5 (evt slå sammen dem to kapitlene)


Med vennlig hilsen,
Håkon Halland Pedersen
Student

Bachelorstudium i informatikk -
design og utvikling av IT-systemer: Datasikkerhet.
Fakultet for informasjonsteknologi,
ingeniørfag og økonomi.
Høgskolen i Østfold

Mobil: +47 924 63 105<tel:+4792463105>
Epost: ***@***.******@***.***>
LinkedIN: https://www.linkedin.com/in/hakonhpedersen/

________________________________
