### ISSUE TITLE
mysql med eller ikke med rammeverket?

### ISSUE THREAD

**Issue by haakonhp** [JarleSyvertsen/EstivateORM#38]

**Comment by JarleSyvertsen** [comment]
MySQL er ikke fullstendig implementert i rammeverket (Krever litt omskriving på driversiden, og det er fort mulig at noen sqlite støttede kommandoer vi bruker ikke er implementert likt på mySQL). Så per nå er den ikke med, og siden vi fikk vite at koden ikke trengtes å utvides så er ikke mysql inkludert i noen praktisk betydning.
