### ISSUE TITLE
mangler get many

### ISSUE THREAD

**Issue by haakonhp** [JarleSyvertsen/EstivateORM#4]

**Comment by JarleSyvertsen** [comment]
Fått grunnleggende implementasjon i release 0.6.0

**Comment by JarleSyvertsen** [comment]
Forbedret denne modulen noe og gitt tilgang til den generiske where slik at brukeren kan legge til vilkårlige restriksjoner. Denne kan chaines uten problem. Sier meg fornøyd med dette, så closer issuet.
